### ISSUE TITLE
[plone5] - Remove formlib imports

### ISSUE THREAD

**Issue by cekk** [PloneGov-IT/rer.bandi#3]
https://github.com/PloneGov-IT/rer.bandi/blob/20cb8a31ca1b4ea0a9553197cf53527a635cffc5/rer/bandi/portlets/collection.py#L14

See how portlets are made in plone 5.1 with z3c.form instead formlib.
You can also clean some stuffs: for example you could extend base collection portlet and add only bando-related fields

**Comment by eikichi18** [comment]
fixed portlets, now maded with z3c.form instead formlib. Code cleaned and fixed output of pubblication date.
