### ISSUE TITLE
Update HISTORY, README and version

### ISSUE THREAD

**Issue by cekk** [PloneGov-IT/rer.bandi#4]
This is a major change, so set version to 3.0.0

Update HISTORY with some generic infos about what you made. For example: "plone 5 compatibility" or "drop AT support and add Dx contents".

Update also README with infos about compatibility.
If this works only on Plone 5, we need to write it (also in setup.py classifiers)

**Comment by eikichi18** [comment]
Updated version on HISTORY file
Updated HISTORY
Updated README
